version: '3.7'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    networks:
      - webnet
    env_file:
      - docker.env
    environment:
      DB_URI: ${DB_URI}
      DB_PORT: ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
  main:
    container_name: main
    build:
      context: .
      target: dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - docker.env
    ports:
      - ${PORT}:${PORT}
    networks:
      - webnet
    depends_on:
      - mongodb
    command: npm run start:dev
networks:
  webnet:
